import _ from "lodash";
import { useFormik } from "formik";

import MuiInput from "components/MuiInputOnBlur";
import Stack from "@mui/material/Stack";

const MultipleFieldsNoMap = () => {
  const formik = useFormik({
    initialValues: {} as any,
    onSubmit: (values, actions) => {
      console.log(values, actions);
    },
  });

  return (
    <>
      Map Print no key
      <form onSubmit={formik.handleSubmit}>
        <Stack>
          {_.map(formik.values, (val, index) => (
            <div key={index}>
              {index} - {val}
            </div>
          ))}
        </Stack>
        <Stack spacing={2} sx={{ width: 600, margin: "auto", padding: 10 }}>
          <MuiInput
            label={`0-field`}
            variant="outlined"
            fullWidth
            name={`0-field`}
            value={formik.values[`0-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`1-field`}
            variant="outlined"
            fullWidth
            name={`1-field`}
            value={formik.values[`1-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`2-field`}
            variant="outlined"
            fullWidth
            name={`2-field`}
            value={formik.values[`2-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`3-field`}
            variant="outlined"
            fullWidth
            name={`3-field`}
            value={formik.values[`3-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`4-field`}
            variant="outlined"
            fullWidth
            name={`4-field`}
            value={formik.values[`4-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`5-field`}
            variant="outlined"
            fullWidth
            name={`5-field`}
            value={formik.values[`5-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`6-field`}
            variant="outlined"
            fullWidth
            name={`6-field`}
            value={formik.values[`6-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`7-field`}
            variant="outlined"
            fullWidth
            name={`7-field`}
            value={formik.values[`7-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`8-field`}
            variant="outlined"
            fullWidth
            name={`8-field`}
            value={formik.values[`8-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`9-field`}
            variant="outlined"
            fullWidth
            name={`9-field`}
            value={formik.values[`9-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`10-field`}
            variant="outlined"
            fullWidth
            name={`10-field`}
            value={formik.values[`10-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`11-field`}
            variant="outlined"
            fullWidth
            name={`11-field`}
            value={formik.values[`11-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`12-field`}
            variant="outlined"
            fullWidth
            name={`12-field`}
            value={formik.values[`12-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`13-field`}
            variant="outlined"
            fullWidth
            name={`13-field`}
            value={formik.values[`13-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`14-field`}
            variant="outlined"
            fullWidth
            name={`14-field`}
            value={formik.values[`14-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`15-field`}
            variant="outlined"
            fullWidth
            name={`15-field`}
            value={formik.values[`15-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`16-field`}
            variant="outlined"
            fullWidth
            name={`16-field`}
            value={formik.values[`16-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`17-field`}
            variant="outlined"
            fullWidth
            name={`17-field`}
            value={formik.values[`17-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`18-field`}
            variant="outlined"
            fullWidth
            name={`18-field`}
            value={formik.values[`18-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`19-field`}
            variant="outlined"
            fullWidth
            name={`19-field`}
            value={formik.values[`19-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`20-field`}
            variant="outlined"
            fullWidth
            name={`20-field`}
            value={formik.values[`20-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`21-field`}
            variant="outlined"
            fullWidth
            name={`21-field`}
            value={formik.values[`21-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`22-field`}
            variant="outlined"
            fullWidth
            name={`22-field`}
            value={formik.values[`22-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`23-field`}
            variant="outlined"
            fullWidth
            name={`23-field`}
            value={formik.values[`23-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`24-field`}
            variant="outlined"
            fullWidth
            name={`24-field`}
            value={formik.values[`24-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`25-field`}
            variant="outlined"
            fullWidth
            name={`25-field`}
            value={formik.values[`25-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`26-field`}
            variant="outlined"
            fullWidth
            name={`26-field`}
            value={formik.values[`26-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`27-field`}
            variant="outlined"
            fullWidth
            name={`27-field`}
            value={formik.values[`27-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`28-field`}
            variant="outlined"
            fullWidth
            name={`28-field`}
            value={formik.values[`28-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`29-field`}
            variant="outlined"
            fullWidth
            name={`29-field`}
            value={formik.values[`29-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`30-field`}
            variant="outlined"
            fullWidth
            name={`30-field`}
            value={formik.values[`30-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`31-field`}
            variant="outlined"
            fullWidth
            name={`31-field`}
            value={formik.values[`31-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`32-field`}
            variant="outlined"
            fullWidth
            name={`32-field`}
            value={formik.values[`32-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`33-field`}
            variant="outlined"
            fullWidth
            name={`33-field`}
            value={formik.values[`33-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`34-field`}
            variant="outlined"
            fullWidth
            name={`34-field`}
            value={formik.values[`34-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`35-field`}
            variant="outlined"
            fullWidth
            name={`35-field`}
            value={formik.values[`35-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`36-field`}
            variant="outlined"
            fullWidth
            name={`36-field`}
            value={formik.values[`36-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`37-field`}
            variant="outlined"
            fullWidth
            name={`37-field`}
            value={formik.values[`37-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`38-field`}
            variant="outlined"
            fullWidth
            name={`38-field`}
            value={formik.values[`38-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`39-field`}
            variant="outlined"
            fullWidth
            name={`39-field`}
            value={formik.values[`39-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`40-field`}
            variant="outlined"
            fullWidth
            name={`40-field`}
            value={formik.values[`40-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`41-field`}
            variant="outlined"
            fullWidth
            name={`41-field`}
            value={formik.values[`41-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`42-field`}
            variant="outlined"
            fullWidth
            name={`42-field`}
            value={formik.values[`42-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`43-field`}
            variant="outlined"
            fullWidth
            name={`43-field`}
            value={formik.values[`43-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`44-field`}
            variant="outlined"
            fullWidth
            name={`44-field`}
            value={formik.values[`44-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`45-field`}
            variant="outlined"
            fullWidth
            name={`45-field`}
            value={formik.values[`45-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`46-field`}
            variant="outlined"
            fullWidth
            name={`46-field`}
            value={formik.values[`46-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`47-field`}
            variant="outlined"
            fullWidth
            name={`47-field`}
            value={formik.values[`47-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`48-field`}
            variant="outlined"
            fullWidth
            name={`48-field`}
            value={formik.values[`48-field`]}
            onChange={formik.handleChange}
          />
          <MuiInput
            label={`49-field`}
            variant="outlined"
            fullWidth
            name={`49-field`}
            value={formik.values[`49-field`]}
            onChange={formik.handleChange}
          />
        </Stack>
      </form>
    </>
  );
};

export default MultipleFieldsNoMap;
